"""empty message

Revision ID: 5506c295f6ac
Revises: b155b68b4673
Create Date: 2026-09-06 15:18:22.597432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5506c295f6ac'
down_revision: Union[str, Sequence[str], None] = 'b155b68b4673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('salary_min_yearly', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('job', sa.Column('salary_max_yearly', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('job', sa.Column('employment_type_norm', sa.String(length=32), nullable=True))
    op.add_column('job', sa.Column('duplicate_of', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'duplicate_of')
    op.drop_column('job', 'employment_type_norm')
    op.drop_column('job', 'salary_max_yearly')
    op.drop_column('job', 'salary_min_yearly')
    # ### end Alembic commands ###
