"""initial tables

Revision ID: b155b68b4673
Revises: 
Create Date: 2026-09-05 12:54:29.810836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b155b68b4673'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_name'), 'company', ['name'], unique=True)
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('area', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_display_name'), 'location', ['display_name'], unique=True)
    op.create_table('raw_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_job_id', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('search_phrase', sa.String(length=120), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_job_id', name='uq_raw_job_source_id')
    )
    op.create_index(op.f('ix_raw_job_source'), 'raw_job', ['source'], unique=False)
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_job_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('salary_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_currency', sa.String(length=3), nullable=True),
    sa.Column('salary_period', sa.String(length=16), nullable=True),
    sa.Column('salary_is_predicted', sa.Boolean(), nullable=True),
    sa.Column('employment_type', sa.String(length=32), nullable=True),
    sa.Column('remote_option', sa.String(length=32), nullable=True),
    sa.Column('category_label', sa.String(length=120), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_job_id', name='uq_job_source_id')
    )
    op.create_index(op.f('ix_job_company_id'), 'job', ['company_id'], unique=False)
    op.create_index(op.f('ix_job_location_id'), 'job', ['location_id'], unique=False)
    op.create_index(op.f('ix_job_posted_at'), 'job', ['posted_at'], unique=False)
    op.create_index(op.f('ix_job_source'), 'job', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_source'), table_name='job')
    op.drop_index(op.f('ix_job_posted_at'), table_name='job')
    op.drop_index(op.f('ix_job_location_id'), table_name='job')
    op.drop_index(op.f('ix_job_company_id'), table_name='job')
    op.drop_table('job')
    op.drop_index(op.f('ix_raw_job_source'), table_name='raw_job')
    op.drop_table('raw_job')
    op.drop_index(op.f('ix_location_display_name'), table_name='location')
    op.drop_table('location')
    op.drop_index(op.f('ix_company_name'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
