"""widen employment_type

Revision ID: b33f834f34d3
Revises: 5506c295f6ac
Create Date: 2026-09-06 23:35:30.851266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b33f834f34d3'
down_revision: Union[str, Sequence[str], None] = '5506c295f6ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job', 'employment_type',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=120),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job', 'employment_type',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    # ### end Alembic commands ###
